-- generated by Claude, more-or-less.

{-# LANGUAGE DeriveAnyClass      #-}
{-# LANGUAGE DeriveGeneric       #-}
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications    #-}
{-# LANGUAGE TypeFamilies        #-}


-- for MonadTerminal
{-# LANGUAGE FlexibleContexts    #-}
{-# LANGUAGE UndecidableInstances #-}

{-# LANGUAGE InstanceSigs #-}

module Main where

import Prelude (Bool(False, True), FilePath, IO, ($), (>>), (<>), (>>=), (/=), return)

import Control.Monad.IO.Class (liftIO)

import Data.Maybe (Maybe(Just, Nothing))

import Data.Proxy (Proxy(..))
import Data.Text (pack)

import System.Console.Haskeline (InputT)

import System.Directory (doesDirectoryExist, setCurrentDirectory)

import System.Environment (lookupEnv)

import System.FilePath ((</>))


import qualified Data.Text  as T

import Database.Persist.Sqlite       (SqliteConf)
import Options.Applicative hiding (many)

import Text.Megaparsec
import Text.Megaparsec.Char

import IntelliMonad.Consume
  ( CommandSpec(..)
  , MonadTerminal(..)
  , Prompt
  , ToolProxy(..)
  , defaultCommands
  , defaultTools
  , readConfig
  , lexm
  , model
  , parseSessionName
  , runRepl
  , fromModel
  )

import Tools.Hello
  (
    Hello
  )

import Tools.ListGitFiles
  (
    ListGitFiles
  )

import Tools.ReadGitFile
  (
    ReadGitFile
  )

import Tools.Man
  (
    Man
  )

-- ── Extra REPL command ────────────────────────────────────────────────────────
greetCommand :: CommandSpec
greetCommand = CommandSpec
  ":greet <name>"
  (try (lexm (string ":greet") >> T.pack <$> lexm parseSessionName) >>= \n ->
     pure $ termOutput $ "Hello from the REPL, " <> n <> "!\n")


-- ── CWD REPL command ────────────────────────────────────────────────────────
cwdCommand :: CommandSpec
cwdCommand = CommandSpec ":cwd <path>"
             (try (lexm (string ":cwd") >> T.pack <$> lexm (many (satisfy (/= '\n'))))
              >>= \p -> pure (handleCwd $ T.unpack p))

handleCwd :: FilePath -> Prompt (InputT IO) ()
handleCwd path = liftIO (doesDirectoryExist (path </> ".git")) >>= \case
  False -> termOutput $ "Fatal: Not a git repository: " <> T.pack path <> "\n"
  True  -> do
    liftIO $ setCurrentDirectory path
    termOutput $ "Git Working directory set to: " <> T.pack path <> "\n"

-- ── Main ──────────────────────────────────────────────────────────────────────

main :: IO ()
main = do
  config     <- readConfig
  modelName  <- lookupEnv "OPENAI_MODEL" >>= \case
    Just m  -> return (pack m)
    Nothing -> return config.model
  sessionName <- pack <$> customExecParser (prefs showHelpOnEmpty)
    (info (argument str (metavar "SESSION_NAME" <> value "default" <> showDefault))
          (fullDesc <> progDesc "hello-repl"))
  runRepl @SqliteConf
          (ToolProxy (Proxy @Hello) :
           ToolProxy (Proxy @ReadGitFile) :
           ToolProxy (Proxy @ListGitFiles) :
           ToolProxy (Proxy @Man) :
           defaultTools )
          (greetCommand :
           cwdCommand :
           defaultCommands @SqliteConf)
          []
          sessionName
          (fromModel modelName)
          []
